# version: '3.8'

services:
  sb-solar-system-api-app:
    build: .
    restart: always
    container_name: sb-solar-system-api-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - sb-solar-system-api-postgresql
      - sb-solar-system-api-mysql
      - sb-solar-system-api-redis
  sb-solar-system-api-postgresql:
    image: postgres:17
    restart: always
    container_name: sb-solar-system-api-postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - sb-solar-system-api-postgresql-data:/var/lib/postgresql/data
  sb-solar-system-api-mysql:
    image: mysql:8.0
    restart: always
    container_name: sb-solar-system-api-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - sb-solar-system-api-mysql-data:/var/lib/mysql
  sb-solar-system-api-redis:
    image: redis:7.2
    restart: always
    container_name: sb-solar-system-api-redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - sb-solar-system-api-redis-data:/var/lib/redis/data
volumes:
  sb-solar-system-api-postgresql-data:
  sb-solar-system-api-mysql-data:
  sb-solar-system-api-redis-data: